import "./globals.css";
import "./lib/hanko/hanko.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import dynamic from "next/dynamic";
import { MobileRightPanelContextProvider } from "./contexts/PanelProviders";
import ModalContextProvider from "./contexts/ModalContextProvider";

const ThemeContextProvider = dynamic(
  () => import("./contexts/ThemeContextProvider"),
  {
    ssr: false,
  }
);

const lato = Lato({ weight: ["300", "400", "700", "900"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <ThemeContextProvider>
          <MobileRightPanelContextProvider>
            <ModalContextProvider>{children}</ModalContextProvider>
          </MobileRightPanelContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
