import "./globals.css";
import "./lib/hanko/hanko.css";
import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import dynamic from "next/dynamic";

const ThemeContextProvider = dynamic(
  () => import("./contexts/ThemeContextProvider"),
  {
    ssr: false,
  }
);

const barlow = Barlow({
  weight: ["300", "400", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <ThemeContextProvider>{children}</ThemeContextProvider>
      </body>
    </html>
  );
}
