import ThemeContextProvider from "./contexts/ThemeContextProvider";
import "./globals.css";
import "./lib/hanko/hanko.css";
import type { Metadata } from "next";
import { Barlow } from "next/font/google";

const barlow = Barlow({
  weight: ["300", "400", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <body className={barlow.className}>{children}</body>
      </ThemeContextProvider>
    </html>
  );
}
